name: scan-vulnerabilities
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Scan
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Manual Trivy Setup
      uses: aquasecurity/setup-trivy@v0.2.0
      with:
        cache: true
        version: v0.57.1

    - name: Run Trivy scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: config
        hide-progress: true
        output: trivy.txt

    - name: Publish Trivy Output to Summary
      run: |
        if [[ -s trivy.txt ]]; then
          {
            echo "### Security Output"
            echo "<details><summary>Click to expand</summary>"
            echo ""
            echo '```terraform'
            cat trivy.txt
            echo '```'
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY
        fi